
INSERT INTO pet(name, species, age, sex, description, breed, adoption_status_id, photo)
VALUES 	('Rosey', 'Dog', 5, 'Female', 'Rosey tends to keep to herself. But when she gets to know you, she flourishes!', 
		'Husky Mix', 1, 
		 'https://images.pexels.com/photos/2607544/pexels-photo-2607544.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1'),
		 ('Rocco', 'Cat', 6, 'Male', 'Rocco is one of our sweetest house cats! Loves fuzzy toys', 'Tom Cat', 1, 
		  'https://images.pexels.com/photos/177809/pexels-photo-177809.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1'),
		  ('Daisy', 'Cat', 5, 'Female', 'Sweet kitten with the most beatiful eyes!', 'Korat', 1, 
		  'https://images.pexels.com/photos/104827/cat-pet-animal-domestic-104827.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1'),
		  ('Max', 'Dog', 1, 'Male', 'The cutest puppy looking for a nice home!', 'Black Lab', 1, 
		   'https://images.pexels.com/photos/59965/dog-young-dog-puppy-59965.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1'),
		    ('Teddy', 'Cat', 2, 'Male', 'If you want a cat that loves cuddles and rolling on the floor, Teddy''s your guy', 
			 'Chartreux', 1, 
			 'https://images.pexels.com/photos/1573324/pexels-photo-1573324.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1'), 
			 ('Marv', 'Frog', 9, 'Male', 'Happy little frog looking for his forever pond!', 'Tree Frog', 1, 
			  'https://images.pexels.com/photos/70083/frog-macro-amphibian-green-70083.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1'),
			  ('Luna', 'Dog', 3, 'Female', 'Luna would love a place to run in the snow!', 'Husky', 1, 
			   'https://images.pexels.com/photos/803766/pexels-photo-803766.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1'), 
			   ('Sadie', 'Cat', 1, 'Female', 'Active little kitten who needs a play pal!', 'Main Coon', 1, 
			   'https://images.pexels.com/photos/2071882/pexels-photo-2071882.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1'), 
			   ('Ace', 'Dog', 1, 'Male', 'Sweet little guy who loves to jump and play!', 'Doodle', 1, 
				'https://images.pexels.com/photos/1458925/pexels-photo-1458925.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1'),
				('Sky', 'Bird', 8, 'Female', 'Loves her bird feed and nesting in her cage!', 'Parakeet', 1, 
				'https://images.pexels.com/photos/2226006/pexels-photo-2226006.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1'), 
				('Bert and Ernie', 'Reptile', 10, 'Males', 'Two for one deal! These two siblings love swimming and chomping on celery!', 
				'Red Eared Turtle', 1, 
				 'https://images.pexels.com/photos/7765015/pexels-photo-7765015.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1'),
				  ('Dumbo','Elephant', 2, 'Male', 'One for our adventurous adopters! Needs lots of space.', 'Grey Elephant', 1, 
				  'https://images.pexels.com/photos/133394/pexels-photo-133394.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1'), 
				  ('Charlie', 'Bird', 4, 'Male', 'Fun talkative bird with a bit of a sassy side', 'Parakeet', 1, 
				  'https://images.pexels.com/photos/4657306/pexels-photo-4657306.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1'), 
				  ('Bella', 'Dog', 3, 'Female', 'One minute Bella will be tearing through the yard, the next asleep on the couch!', 
				  'French Bulldog', 1, 'https://images.pexels.com/photos/160846/french-bulldog-summer-smile-joy-160846.jpeg');
